<?php

declare(strict_types=1);

namespace JotformBridge\Templates;

use JotformBridge\Forms\FieldNormalizer;
use JotformBridge\Forms\FormSchema;
use JotformBridge\Integrations\Integration;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Writes the starting point of a custom template out of a synced schema.
 *
 * The identifiers a template addresses — `email`, `full_name.first` — are
 * derived from the Jotform form, and until now a developer retyped them by
 * hand from the field list on the admin screen. A typo there is not caught by
 * anything until the template is scanned, or worse, until a visitor submits and
 * the validator refuses a field the form does not have. The schema already
 * knows every valid key, so there is no reason for anybody to type one.
 *
 * What comes out is a plain file: no framework, no partials, no CSS. Only the
 * `data-jotform-*` attributes carry meaning; everything around them is there to
 * be replaced. That is the whole point of writing a template rather than using
 * the automatic renderer, so the scaffold must not look like something that
 * wants to stay as it is.
 *
 * Nothing is written to disk. The theme directory belongs to the theme, write
 * access is not a given, and a file that appears without being asked for is
 * worse than no file. The output is text for a human to paste.
 */
final class TemplateScaffold
{
    /**
     * @return string PHP source for `wp-content/themes/<theme>/jotform-bridge-templates/<slug>.php`.
     */
    public function build(Integration $integration, FormSchema $schema): string
    {
        $slug = $integration->slug() !== '' ? $integration->slug() : 'form';
        $name = $integration->name() !== '' ? $integration->name() : $slug;

        $fields = '';

        foreach ($schema->supportedFields() as $field) {
            $fields .= $field['children'] !== []
                ? $this->composite($field, $slug)
                : $this->scalar($field, $slug);
        }

        return $this->header($name, $slug)
            . $this->openForm($slug)
            . $fields
            . $this->closeForm();
    }

    public function fileName(Integration $integration): string
    {
        return ($integration->slug() !== '' ? $integration->slug() : 'form') . '.php';
    }

    private function header(string $name, string $slug): string
    {
        return <<<PHP
<?php
/**
 * Jotform Template Name: {$this->text($name)}
 *
 * Starting point generated by Jotform Bridge from the synced Jotform schema.
 * Restyle it however you like: only the data-jotform-* attributes are
 * load-bearing, everything else is here to be replaced.
 *
 * Save it as {$slug}.php: the file name is the slug an integration points at,
 * so renaming the file means picking the template again.
 *
 * Do not add a Jotform form ID here — which form this submits to belongs to
 * the integration, not to the template.
 *
 * @var array<string, string> \$integration Slug, name and template slug.
 * @var array<string, mixed>  \$schema      Fields and required paths.
 * @var string                \$endpoint    Where the form posts.
 * @var string                \$honeypot    Anti-spam decoy, print it as is.
 * @var string                \$turnstile   Challenge widget, empty unless configured.
 */

if (!defined('ABSPATH')) {
    exit;
}
?>

PHP;
    }

    private function openForm(string $slug): string
    {
        return <<<PHP
<form
    class="{$slug}-form"
    method="post"
    action="<?php echo esc_url(\$endpoint); ?>"
    data-jotform-bridge
    data-jotform-integration="{$slug}"
    novalidate
>
    <p class="{$slug}-form__success" data-jotform-success role="status" aria-live="polite"></p>
    <div class="{$slug}-form__errors" data-jotform-errors role="alert" aria-live="assertive"></div>

    <?php // Escaped by the plugin; print them as they are. ?>
    <?php echo \$honeypot; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
    <?php echo \$turnstile; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>


PHP;
    }

    private function closeForm(): string
    {
        return <<<PHP
    <p class="form-actions">
        <button type="submit">Send</button>
    </p>
</form>

PHP;
    }

    /**
     * @param array<string, mixed> $field
     */
    private function composite(array $field, string $slug): string
    {
        $out = sprintf("    <fieldset>\n        <legend>%s</legend>\n", $this->text((string) $field['label']));

        foreach ($field['children'] as $child) {
            $key   = (string) $child['key'];
            $id    = $this->id($slug, $key);
            $label = (string) $child['label'] !== '' ? (string) $child['label'] : $key;

            $out .= sprintf(
                "        <p>\n"
                . "            <label for=\"%s\">%s</label>\n"
                . "            <input type=\"text\" id=\"%s\" data-jotform-field=\"%s\" aria-describedby=\"%s-error\"%s>\n"
                . "            <span class=\"field-error\" id=\"%s-error\" data-jotform-field-error=\"%s\"></span>\n"
                . "        </p>\n",
                $id,
                $this->text($label),
                $id,
                $key,
                $id,
                (bool) $child['required'] ? ' required' : '',
                $id,
                $key
            );
        }

        return $out . "    </fieldset>\n\n";
    }

    /**
     * @param array<string, mixed> $field
     */
    private function scalar(array $field, string $slug): string
    {
        $key      = (string) $field['key'];
        $id       = $this->id($slug, $key);
        $type     = (string) $field['type'];
        $required = (bool) $field['required'];
        $label    = (string) $field['label'] !== '' ? (string) $field['label'] : $key;

        if ($type === FieldNormalizer::TYPE_RADIO || $type === FieldNormalizer::TYPE_CHECKBOX) {
            return $this->choiceGroup($field, $id, $key, $label, $type, $required);
        }

        if ($type === FieldNormalizer::TYPE_TEXTAREA) {
            $control = sprintf(
                '<textarea id="%s" rows="6" data-jotform-field="%s" aria-describedby="%s-error"%s></textarea>',
                $id,
                $key,
                $id,
                $required ? ' required' : ''
            );
        } elseif ($type === FieldNormalizer::TYPE_SELECT) {
            $options = '';

            foreach ($field['options'] as $option) {
                $options .= sprintf(
                    "\n                <option value=\"%s\">%s</option>",
                    $this->text((string) $option['value']),
                    $this->text((string) $option['label'])
                );
            }

            $control = sprintf(
                '<select id="%s" data-jotform-field="%s" aria-describedby="%s-error"%s>'
                . "\n                <option value=\"\">—</option>%s\n            </select>",
                $id,
                $key,
                $id,
                $required ? ' required' : '',
                $options
            );
        } else {
            $control = sprintf(
                '<input type="%s" id="%s" data-jotform-field="%s" aria-describedby="%s-error"%s>',
                $this->inputType($type),
                $id,
                $key,
                $id,
                $required ? ' required' : ''
            );
        }

        return sprintf(
            "    <p>\n"
            . "        <label for=\"%s\">%s</label>\n"
            . "        %s\n"
            . "        <span class=\"field-error\" id=\"%s-error\" data-jotform-field-error=\"%s\"></span>\n"
            . "    </p>\n\n",
            $id,
            $this->text($label),
            $control,
            $id,
            $key
        );
    }

    /**
     * @param array<string, mixed> $field
     */
    private function choiceGroup(
        array $field,
        string $id,
        string $key,
        string $label,
        string $type,
        bool $required
    ): string {
        $inputType = $type === FieldNormalizer::TYPE_RADIO ? 'radio' : 'checkbox';
        $choices   = '';
        $index     = 0;

        foreach ($field['options'] as $option) {
            $optionId = $id . '-' . ++$index;

            $choices .= sprintf(
                "        <label for=\"%s\">\n"
                . "            <input type=\"%s\" id=\"%s\" name=\"%s\" value=\"%s\" data-jotform-field=\"%s\"\n"
                . "                aria-describedby=\"%s-error\"%s>\n"
                . "            %s\n"
                . "        </label>\n",
                $optionId,
                $inputType,
                $optionId,
                $id,
                $this->text((string) $option['value']),
                $key,
                // Every input of the group describes itself by the one slot the
                // group shares, below. Without it the server's message lands in
                // an element nothing points at, and a screen reader announces
                // the group as invalid without ever saying why.
                $id,
                // A required radio group is satisfied by any one input; a
                // required checkbox group is not, so the server decides.
                $required && $inputType === 'radio' ? ' required' : '',
                $this->text((string) $option['label'])
            );
        }

        return sprintf(
            "    <fieldset>\n        <legend>%s</legend>\n%s"
            . "        <span class=\"field-error\" id=\"%s-error\" data-jotform-field-error=\"%s\"></span>\n"
            . "    </fieldset>\n\n",
            $this->text($label),
            $choices,
            $id,
            $key
        );
    }

    private function inputType(string $type): string
    {
        $map = [
            FieldNormalizer::TYPE_EMAIL  => 'email',
            FieldNormalizer::TYPE_PHONE  => 'tel',
            FieldNormalizer::TYPE_NUMBER => 'number',
        ];

        return $map[$type] ?? 'text';
    }

    private function id(string $slug, string $key): string
    {
        return $slug . '-' . str_replace(['.', '_'], '-', $key);
    }

    /**
     * Escapes label text into the generated source.
     *
     * The result is static markup in somebody's theme, so it is escaped once
     * here rather than left for a runtime call the developer might delete while
     * restyling. A label carrying a quote or an angle bracket — Jotform allows
     * both — must not be able to break the file it lands in.
     */
    private function text(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }
}
